import React from 'react'
import type {Metadata} from 'next'
import {Inter as FontSans} from 'next/font/google'
import './globals.css'
// 🐶 importe `ThemeProvider` et `cn`
// 🤖
// import {ThemeProvider} from '@/components/theme-provider'
// import {cn} from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      {/* 🐶 utilise `cn` pour merger 'fontSans.variable' et les propriétés tailwind
          suivante : 'min-h-screen bg-background font-sans antialiased'
          doc : https://ui.shadcn.com/docs/installation/next
      */}
      <body className={fontSans.variable}>
        {/* 🐶 wrap {children} du theme provider  
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          > */}
        {children}
      </body>
    </html>
  )
}
